### PR TITLE
update `cookie` to v0.11 to pull in latest `ring`

### PR DESCRIPTION
**Pull request by rushmorem**

### CODE REVIEW

**Comment by jebrosen** [comment]
This cannot be done in `0.3`, and the commit that `master` points to is identical to cookie 0.11 except for the stated version number.

See the links in https://github.com/SergioBenitez/Rocket/issues/687#issuecomment-402843320.

**Comment by rushmorem** [comment]
> This cannot be done in 0.3

This pull request does not make any assumption about Rocket's version. `Cargo.toml` is already set to `0.4.0-dev`.

> the commit that master points to is identical to cookie 0.11 except for the stated version number

Since they are equivalent, why not just use the version number, now that it's up on `crates.io`?

**Comment by jebrosen** [comment]
> This pull request does not make any assumption about Rocket's version. Cargo.toml is already set to 0.4.0-dev.

Sorry, thinking you actually wanted this for 0.3 was a hasty assumption on my part given the number of past requests to do it.

> Since they are equivalent, why not just use the version number, now that it's up on crates.io?

I see no problem with doing this now, assuming cookie 0.11 has all of the features Rocket 0.4 will need.

**Comment by SergioBenitez** [comment]
We're already depending on a `cookie` that depends on `0.13` (since e25a82b14b). This change would have no affect on which version of `ring` is used.

**Pull request closed without merging**
