### PR TITLE
Very simple CORS implementation

### PR DESCRIPTION
**Pull request by impowski**
Due to this issue #25, I rewrote what @SergioBenitez posted in this [post](https://github.com/SergioBenitez/Rocket/issues/25#issuecomment-271065434). There is still no middleware-like functionality and this is a very basic implementation.

### CODE REVIEW

**Comment by mehcode** [comment]
I feel I must comment on how nested these Responders are getting. Does Rocket not have a way to add middleware to a group of routes?

Something like CORS is something you likely want to enable or disable with similar options for the vast majority of your routes and having to add `CORS` everywhere is a bit intense. 

I'd vote to work on middleware support in Rocket before adding this.

**Comment by impowski** [comment]
@mehcode Yeah, I had a discussion about middlewares with @SergioBenitez on IRC, he said that it will be available soon, but I guess we must take on it and help him, at least he could mentor us a little so it would be idiomatic with Rocket and how he is seeing it.

**Comment by SergioBenitez** [comment]
@impowski Thank you for packaging up the `CORS` implementation in #25 into a nice PR!

Unfortunately, I don't feel that this is a good fit for `contrib` for exactly the reason discussed: middleware (fairings) provide a much better solution here. Let's instead work to find a great design for fairings instead of encouraging a suboptimal one. As a stop-gap measure, feel free to create a `rocket-cors` crate with this functionality.

Closing this PR for the above reasons.

**Comment by Enether** [comment]
Please do create a `rocket-cors` crate for a way to get around the missing functionality for now

**Comment by onelson** [comment]
@Enether I think I'm about to drop this into a toy project -- I'll see about publishing a crate if @impowski doesn't beat us to it. Seems like a decent workaround for the time being, and it's essential to making my app (and yours?) work.

**Comment by onelson** [comment]
Just got a drive-by PR on it from @Enether, so I guess the cat is out of the bag. https://github.com/onelson/rocket_cors is a thing, at least for now. There are some typos in the readme, etc, but I'll aim to get a couple tests/examples added before pushing to crates.io. Perhaps @impowski will want to take it off my hands and publish it himself? That'd be fine by me.

**Pull request closed without merging**
