### PR TITLE
Add Font Content Types

### PR DESCRIPTION
**Pull request by mmstick**
Adds support for TTF, OTF, WOFF, and WOFF2 content types, in addition to fixing a few Clippy concerns in the file. Also added WEBP.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Can you point me to an authoritative resource on the selection of these Content-Types?

**Comment by mmstick** [comment]
- https://www.iana.org/assignments/media-types/media-types.xhtml
- TTF/OTF: http://www.iana.org/assignments/media-types/application/font-sfnt
- WOFF: http://www.iana.org/assignments/media-types/application/font-woff
- WOFF2: http://www.iana.org/assignments/media-types/font/woff2

Although it seems there's also support for `font/ttf` and `font/otf`.

**Comment by SergioBenitez** [comment]
According to [this IETF document](https://datatracker.ietf.org/doc/draft-ietf-justfont-toplevel/), the `font` top-level MIME type is still being reviewed; it is a _draft_.

**Comment by mmstick** [comment]
The newish WOFF2 format requires the new top level MIME type, hence why I'm
using it for WOFF2.

**Comment by SergioBenitez** [comment]
Hmm, yeah.

Can you commit to monitoring that proposal and updating these content-types when it goes through?

**Comment by mmstick** [comment]
Sure thing

**Comment by SergioBenitez** [comment]
Thanks!

Merged in https://github.com/SergioBenitez/Rocket/commit/4161949a1cbd16fa9f3ceb228528c105087529f6.

**Pull request closed without merging**
