### PR TITLE
Bump cookie crate to 0.12.

### PR DESCRIPTION
**Pull request by brndnmtthws**
This fixes the dependency issues with cookie (as mentioned in #975).

### CODE REVIEW

**Comment by brndnmtthws** [comment]
I forgot about that conflict with `hyper-sync-rustls`. On my build I just disable TLS because it's broken.

**Comment by jebrosen** [comment]
Yeah, `hyper-sync-rustls` would need to be bumped first. I'm pretty sure that and `cookie` are the only things that use `ring`.

**Comment by SergioBenitez** [comment]
Just published `hyper-sync-rustls v0.3.0-rc.5`.

**Comment by brndnmtthws** [comment]
Updated with latest `hyper-sync-rustls`.

**Comment by Pierozi** [comment]
I'm using `jsonwebtoken` which are in conflict. I cannot even downgrade to `5.0.1` because the feature related to encryption ES256 are not present.

**Comment by jebrosen** [comment]
Merged in ba6aa2f along with other *ring* dependencies.

**Pull request closed without merging**
