### PR TITLE
Add support for memcache connection pool in rocket_contrib

### PR DESCRIPTION
**Pull request by aisk**

### CODE REVIEW

**Comment by jebrosen** [comment]
I think this looks good. @ELD?

**Comment by ELD** [comment]
@jebrosen Yep, looks good to me. Thanks for the ping. Wouldn't likely have seen this otherwise.

**Comment by aisk** [comment]
Hi, what should I do before this PR merged?

**Comment by aisk** [comment]
Thanks! I tried using this to connect a memcache in a Rocket app, it works.

**Comment by aisk** [comment]
And sorry I'm not push this, I think you can do it when you have time. I know it's hard to maintain such a open source project. :)

**Comment by jebrosen** [comment]
Merged this in 5ce43ed after a brief test. Thanks!

**Pull request closed without merging**
