### PR TITLE
Add impl FromParam,FromFormValue for NonZero* types

### PR DESCRIPTION
**Pull request by dima74**

### CODE REVIEW

**Comment by jebrosen** [comment]
My gut reaction is "why?", but I suppose "why not?" is equally valid considering we implement `FromParam` for pretty much everything that implements `FromStr`.

Docs would need to be updated as well (https://api.rocket.rs/v0.4/rocket/request/trait.FromParam.html#provided-implementations).

**Comment by dima74** [comment]
@jebrosen yes, docs were updated, also added FromFormValue implementations.

**Comment by SergioBenitez** [comment]
In the documentation, can we split the one point line with all of the types into two? That is, have one line for non-`NonZero` types and another specifically calling them out.

**Comment by dima74** [comment]
@SergioBenitez yes, like this:
image

or maybe make three groups? Like this:
image

**Comment by SergioBenitez** [comment]
I like the three groups! Let's go with that one.

**Comment by dima74** [comment]
@SergioBenitez ok, updated

**Comment by SergioBenitez** [comment]
Merged in c100a9212735928ed5ada2a38754a21247c86677. Thank you!

**Pull request closed without merging**
