### PR TITLE
match percent decoded urls #880

### PR DESCRIPTION
**Pull request by PSeitz**
Fixes https://github.com/SergioBenitez/Rocket/issues/880

### CODE REVIEW

**Comment by PSeitz** [comment]
I wanted to add a test for this, but the percent decoding is only in the hyper conversion and does not apply here.


```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/$world")]
fn world() -> &'static str {
    "Hello, $world!"
}

fn rocket() -> rocket::Rocket {
    rocket::ignite().mount("/", routes![world])
}

mod tests {
    use super::*;
    use rocket::local::Client;
    use rocket::http::{Status};

    #[test]
    fn uri_get_original_route() {
        let client = Client::new(rocket()).unwrap();
        let mut response = client.get("/$world").dispatch();
        assert_eq!(response.status(), Status::Ok);
        assert_eq!(response.body_string().unwrap(), format!("Hello, $world!"));
    }

    #[test]
    fn uri_get_url_encoded_route() {
        let client = Client::new(rocket()).unwrap();
        let mut response = client.get("/%24world").dispatch();
        assert_eq!(response.status(), Status::Ok);
        assert_eq!(response.body_string().unwrap(), format!("Hello, $world!"));
    }
}
```

**Comment by PSeitz** [comment]
Tests fail, because of unrelated rustup issue: https://github.com/rust-lang/rust/issues/57488

**Comment by jebrosen** [comment]
This will need tests for sure if it's to be accepted. Even then, I'm hesitant to review any changes that might be rendered obsolete by the hyper upgrade so I'll wait to hear from @SergioBenitez on this.

**Comment by SergioBenitez** [comment]
We definitely need tests. This, or anything like this, won't be accepted without them.

@PSeitz Do those tests pass now? I'd wager no, and that's a concern: we can't have the local client act differently than the "real" client, otherwise testing can't be trusted. In other words, we need to ensure that whatever fix we apply here applies universally.

**Comment by jebrosen** [comment]
> @jebrosen I think whatever we do here we'll need to do when we upgrade hyper, so there's no harm in accepting this now, as far as I can see.

I meant to imply that hyper might even do this itself in newer versions, and that I'd rather we look carefully at the URL handling before implementing it.

That being said, it's a relatively small change in terms of code and any tests written now should apply in the future as well.

**Comment by SergioBenitez** [comment]
> I meant to imply that hyper might even do this itself in newer versions, and that I'd rather we look carefully at the URL handling before implementing it.

I'd consider Hyper "wrong" if it did; it shouldn't be interpreting URIs in any way, given where it wants to sit in the stack. If it does, we should be able to work around it.

**Comment by PSeitz** [comment]
@SergioBenitez I rechecked, but I couldn't find a common entry for the tests and hyper. `from_hyp` uses `Origin::parse_owned(string: String)`, the tests with local request use `Origin::parse(string: &'a str)`, meaning the tests would need to replicate the behaviour.

https://github.com/SergioBenitez/Rocket/blob/5ce43ed4e97261272bbe7d506c534750db71aa32/core/lib/src/local/request.rs#L402-L404

**Comment by PSeitz** [comment]
Actually `Origin::parse(string: &'a str)` is a common entry point, but I can't apply the escaping there because of lifetime issues.

**Review by SergioBenitez — COMMENTED** [review]
While taking a look at resolving the underlying issue, I took a look at this PR. Unfortunately this is incorrect. Decoding needs to be applied _after_ all delimiter-based splits have been applied or else risk introducing new splits. For example, `/a/b%2Fc/d` should result in being decoded in a path with 3 components `a`, `b/c`, `d`, but this PR would result in a path with 4 components `a`, `b`, `c`, and `d`. The same issue occurs with `?` and with `&` and `=` in query parts.

This is incredibly tricky to get right _and_ make perform well. I'm working now on a fix to this issue.

**Pull request closed without merging**
