### PR TITLE
Add feature list on the documentation

### PR DESCRIPTION
**Pull request by adelarsq**
Add nightly feature list on the documentation.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
I'm not sure that this belongs in the `README`. Can you tell me why you think it should be there?

**Comment by adelarsq** [comment]
@SergioBenitez Most likely. Are there any other place where this information can be available? I just think that is a relevant information about why nightly is needed actually.

**Comment by shssoichiro** [comment]
You can always find the list of feature flags in the [`lib.rs`](https://github.com/SergioBenitez/Rocket/blob/v0.2.0/lib/src/lib.rs#L1-L7) at the root of the crate.

**Comment by SergioBenitez** [comment]
https://github.com/SergioBenitez/Rocket/issues/19 should be the canonical source for this. I've updated the initial comment with the full list of features.

**Comment by adelarsq** [comment]
@SergioBenitez thanks

**Pull request closed without merging**
