### PR TITLE
Update hyper to 0.10.15

### PR DESCRIPTION
**Pull request by dvic**
https://github.com/hyperium/hyper/compare/v0.10.13...v0.10.15

### CODE REVIEW

**Comment by dvic** [comment]
Seems there is an issue on TravisCI? 

```
error: failed to parse url: nightly/2019-01-10/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz
info: caused by: relative URL without a base
11.49s$ curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
info: downloading installer
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2019-01-10, rust version 1.33.0-nightly (6ecad3383 2019-01-09)
info: downloading component 'rustc'
error: failed to parse url: nightly/2019-01-10/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz
info: caused by: relative URL without a base
The command "curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y" failed and exited with 1 during .
```

**Comment by jebrosen** [comment]
This doesn't seem necessary -- `cargo` already pulls in `0.10.15`, and Rocket doesn't actually depend on any of those changes in `hyper`.

**Comment by dvic** [comment]
Cool, I didn't know one can be certain that Cargo will pull `0.10.15`. For me it's important to stay up to date and, from what I can see in the diff, `0.10.15` had some fixes.

**Comment by jebrosen** [comment]
> Cool, I didn't know one can be certain that Cargo will pull `0.10.15`.

It will only do so if you run `cargo update`, but the specification `0.10.13` means `>= 0.10.13, < 0.11` which does include `0.10.15`.

**Pull request closed without merging**
