### PR TITLE
Fix minor typo

### PR DESCRIPTION
**Pull request by sgrif**

### CODE REVIEW

**Comment by sgrif** [comment]
Just a heads up, it looks like the CI is on a private setup and not the OSS travis infrastructure, so I'm unable to see the CI build that failed.

**Comment by sgrif** [comment]
If the badge in the README is to be believed though, master is failing, not this PR

**Comment by SergioBenitez** [comment]
Yeah, the CI is on a private setup. It's not clear to me how to transition it over to a public one, and the Travis folks are on holiday. So I'll wait until they're back.

Anyway, master (and your PR) are building okay. Travis/Cargo/something gets confused when the version changes, so I have to manually clear the Travis cache and restart the build. I'll need to find a better solution to this.

**Comment by SergioBenitez** [comment]
Merged in https://github.com/SergioBenitez/Rocket/commit/eb8d973abd56dd51e50167726c05825337dbb1a4.

**Pull request closed without merging**
