### PR TITLE
Added known extensions for cbz, cbr, rar and epub

### PR DESCRIPTION
**Pull request by aaronleopold**
Closes https://github.com/SergioBenitez/Rocket/issues/2220

IANA Links:
- [cbr](https://www.iana.org/assignments/media-types/application/vnd.comicbook-rar)
- [cbz](https://www.iana.org/assignments/media-types/application/vnd.comicbook+zip)
- [rar](https://www.iana.org/assignments/media-types/application/vnd.rar)
- [epub](https://www.iana.org/assignments/media-types/application/epub+zip)

### CODE REVIEW

**Comment by aaronleopold** [comment]
Updated to add:
- [opf](https://www.iana.org/assignments/media-types/application/oebps-package+xml)
- [xhtml](https://www.iana.org/assignments/media-types/application/xhtml+xml)

**Comment by aaronleopold** [comment]
Hello @SergioBenitez, any changes you want me to make to get this PR in?

**Comment by aaronleopold** [comment]
Closed as I migrated off Rocket. If you feel you'd like these changes at some point, I'll reopen 👍

**Comment by SergioBenitez** [comment]
Sorry to see you go! Please do reopen the PR! I'm working my way through every issue and PR in the next week.

**Comment by aaronleopold** [comment]
Ah okay, sorry about that - I'll reopen it then

**Comment by SergioBenitez** [comment]
This was merged in c8b8b2b022fc2aa4befba80729d85ae4be9d6d47. Thank you!

**Pull request closed without merging**
