### PR TITLE
Moving `toml` to a newer version

### PR DESCRIPTION
**Pull request by impowski**
Right now everything works just like that, and I'm thinking about implementing it a `serde` way with `Deserialize` and everything else, to be more idiomatic and to drop such functions as `set`, because they look really ugly.

Note for @SergioBenitez : I want this PR to be merged before #204 , because I'm planning to change methods inside of `Config`

### CODE REVIEW

**Comment by SergioBenitez** [comment]
What's the advantage of this? It looks like it introduces more code. What are we winning?

**Comment by SergioBenitez** [comment]
Ping!

**Comment by impowski** [comment]
I'll take a little bit time to check wether I able to simplify it or not.

**Comment by SergioBenitez** [comment]
@impowski Can you state why we should upgrade?

**Comment by SergioBenitez** [comment]
Closing this out.

**Pull request closed without merging**
