### PR TITLE
Implements #267

### PR DESCRIPTION
**Pull request by belst**
This implements `std::convert::From` for `Stream<T>`

implements #267

### CODE REVIEW

**Comment by SergioBenitez** [comment]
`From` doesn't need to be imported; it's in the prelude. Also, we should get rid of the old `from` method. Finally, the new `from` method should have a docstring, likely just a copy of the old one.

Oh, and can we keep using 'Stream::from` in the library? I like the explicitness.

**Comment by belst** [comment]
yeah. I derped a little there :P should be good now I guess.

**Comment by SergioBenitez** [comment]
Should the comment be on the `impl` or on the `fn`? I forget how rustdoc shows the two. Can you see what the difference is?

**Comment by SergioBenitez** [comment]
Merged in 0e759edf78a696f8fc3ffcd7f181720dace2382d.

**Pull request closed without merging**
