### PR TITLE
[WIP] Replace log with slog

### PR DESCRIPTION
**Pull request by mehcode**
This is a _spike_ to get Rocket compiling with slog instead of log. It's nowhere near complete. I'll be working on it for the next week at least.

```
Jan 30 10:52:23.674 INFO 🔧  Configured for development.
Jan 30 10:52:23.674 INFO address: localhost
Jan 30 10:52:23.675 INFO port: 8000
Jan 30 10:52:23.675 INFO log: normal
Jan 30 10:52:23.675 INFO workers: 8
Jan 30 10:52:23.675 INFO session key: present
Jan 30 10:52:23.675 WARN Signing and encryption of cookies is currently disabled.
Jan 30 10:52:23.675 WARN See https://github.com/SergioBenitez/Rocket/issues/20 for info.
Jan 30 10:52:23.675 INFO 🛰  Mounting '/':
Jan 30 10:52:23.676 INFO GET /
Jan 30 10:52:23.676 INFO 🚀  Rocket has launched from http://localhost:8000...
Jan 30 10:52:25.804 INFO GET /:
Jan 30 10:52:25.806 INFO Matched: GET /
Jan 30 10:52:25.806 INFO Hi Everyone!, Stuff: Things
Jan 30 10:52:25.806 INFO Outcome: Success
Jan 30 10:52:25.806 INFO Response succeeded.
Jan 30 10:52:26.944 INFO GET /:
Jan 30 10:52:26.944 INFO Matched: GET /
Jan 30 10:52:26.944 INFO Hi Everyone!, Stuff: Things
Jan 30 10:52:26.945 INFO Outcome: Success
Jan 30 10:52:26.945 INFO Response succeeded.
```
 - [x] Re-structure log invocations to forward arguments in the way that slog expects

 - [x] Re-structure start-up logs to be more friendly with slog. Here's an example of how they could look from some experimenting (outside of the code-base):

```
🔧 Configure: Development
  Jan 30 10:28:32.005 DEBG Address: localhost
  Jan 30 10:28:32.006 DEBG Port: 8080
  Jan 30 10:28:32.006 DEBG Workers: 8
🛰  Mount: /
  Jan 30 10:28:32.006 DEBG GET /
Jan 30 10:28:32.006 INFO 🚀 Rocket has launched from http://localhost:8000...
```

 - [x] ~Add _versions_ to the startup logs: Rust, Rocket, and _Project_~

 - [x] Determine ideal method to allow a configurable drain. My initial thought is a method on the Rocket struct that would accept a function that returns a configured drain. My second thought is to utilize `Rocket.toml` and forward a `log` table to https://github.com/slog-rs/config . I'm leaning towards the latter right now (as its more ergonomic).

 - [x] Do research to determine the ideal format for request logs.

    What I think a request log should contain:
      - Timestamp [info]
      - Path / "Matched" [info]
      - Parameters (could include request guards) [debug]
      - Response "Status Code" [info]
      - Request IP (in production) [info]

---

@SergioBenitez After I get things to a point where I like them. I'll be going through your requirements to make sure we satisfy as many as possible.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Cool, looking forward to seeing progress on this!

**Comment by LauriM** [comment]
Could this open possibilities for hiding the emojis more effectively?

(Reference to the first attempt https://github.com/SergioBenitez/Rocket/pull/84, a bit hackish way to hide them.)

**Comment by mehcode** [comment]
@LauriM Yep. You could easily make a drain adapter that filtered them out.

**Comment by mehcode** [comment]
Ok. This is a lot closer to being done.

---

 - Rocket exposes standard logging macros. These do nothing until after `rocket::ignite` (or `rocket::custom`). 

 - The exposed logging macros support both a compatibility usage and a structured usage.

```rust
// Compatibility with standard log
info!("Matched {}", param);

// Structured usage
info!("Matched"; "Param" => param);
```

---

```
🔧  Configure: development
  Feb 07 09:29:17.382 INFO address: localhost
  Feb 07 09:29:17.383 INFO port: 8000
  Feb 07 09:29:17.383 INFO log: normal
  Feb 07 09:29:17.383 INFO workers: 8
  Feb 07 09:29:17.383 INFO session key: present
Feb 07 09:29:17.383 WARN Signing and encryption of cookies is currently disabled.
Feb 07 09:29:17.383 WARN See https://github.com/SergioBenitez/Rocket/issues/20 for info.
🛰  Mount: /
  Feb 07 09:29:17.383 INFO GET /<id_int>
  Feb 07 09:29:17.383 INFO GET /<id_str>
Feb 07 09:29:17.383 WARN GET /<id_int> and GET /<id_str> collide!
Feb 07 09:29:17.383 WARN Route collisions detected!
Feb 07 09:29:17.384 INFO 🚀  Rocket has launched from http://localhost:8000...
Request: GET /test, IP: [::1]:42248
  Feb 07 09:29:20.420 INFO Matched: GET /<id_int>
    => Failed to parse 'id_int': "test"
  Feb 07 09:29:20.420 INFO Outcome: Forward
  Feb 07 09:29:20.420 INFO Matched: GET /<id_str>
  Feb 07 09:29:20.421 INFO Outcome: Success
  Feb 07 09:29:20.421 INFO Response: 200 OK
Request: GET /1245, IP: [::1]:42252
  Feb 07 09:30:06.216 INFO Matched: GET /<id_int>
  Feb 07 09:30:06.216 INFO Outcome: Success
  Feb 07 09:30:06.216 INFO Response: 200 OK
```

selection_034

**Comment by mehcode** [comment]
@SergioBenitez It's ready for you to try out (and anyone else interested).

In order for the request scoping to work properly (try sending two like requests consecutively to see the issue) we need some unique bit of information per request. It only needs to be unique among all concurrent requests and be different from the previous ID. We could use a simple, small random alphanumeric string here. Thoughts?

**Comment by mehcode** [comment]
Custom drains can now easily be used.

```rust
#![feature(plugin)]
#![plugin(rocket_codegen)]

#[macro_use]
extern crate rocket;

#[macro_use(o)]
extern crate slog;
extern crate slog_stream;
extern crate slog_json;

use rocket::config::{Config, Environment};

use slog::DrainExt;

#[get("/<id_int>")]
fn index_i(id_int: i32) -> String {
    format!("Hello: {}!", id_int)
}

#[get("/<id_str>")]
fn index_s(id_str: String) -> String {
    format!("Hello: {}!", id_str)
}

fn main() {
    let logger = slog::Logger::root(
        slog_stream::stream(
            std::io::stderr(),
            slog_json::default()
        ).fuse(),
        o!("build-id" => "8dfljdf")
    );

    rocket::custom(
        Config::build(Environment::active().unwrap()).log(logger).unwrap()
    ).mount("/", routes![index_i, index_s]).launch();
}
```

**Comment by SergioBenitez** [comment]
@mehcode Your changes are not building. See the Travis log for details.

**Comment by mehcode** [comment]
@SergioBenitez There are at least 2 doc tests failing and I apparently don't know enough about doc tests to fix it. Let's review this and talk about it before I dive into that.

**Comment by impowski** [comment]
@mehcode I had a problem with docs tests too, as I understood that if you have a rust code inside of your docs you need it should be valid with all needed `use` and other things.

**Comment by SergioBenitez** [comment]
What's the status of this, @mehcode? How are you doing regarding my "requirements"?

**Comment by mehcode** [comment]
@SergioBenitez Honestly I was hoping to get some feedback on how it looks so far before I dive deeper. As in, give this branch a go and see if you like:
 - How the logging feels on the console
 - How it feels to make your own drain/logger configuration

**Comment by SergioBenitez** [comment]
@mehcode Can you rebase this on master so I can give it a try?

**Comment by SergioBenitez** [comment]
Why is logging showing up in all of the testing?

**Comment by JeffBelgum** [comment]
@mehcode I was wondering if there's any movement on this. It's something I find I'm in need of for a project I'm working on. Cheers!

**Comment by SergioBenitez** [comment]
@JeffBelgum Out of curiosity, which part of this do you find that you need?

**Comment by JeffBelgum** [comment]
I need the ability to customize the format of log information to include things like timestamp, request ip, file name and line number, etc. I'd also like to remove emojis and colors.

**Comment by SergioBenitez** [comment]
Checking in; what's the status of this?

**Comment by 3Hren** [comment]
JFYI, in my project I've ended up with 3200% CPU consumption in multithreaded application at about 6.2k RPS load and perf shows that there is `slog` spinning around atomic writes/loads.

image

**Comment by mehcode** [comment]
@3Hren This isn't very optimized at the moment. For instance it uses sync logging rather than async. I'd also be interested to see how you're getting those benchmarks as there are very few logs that actually happen during production at the moment.

---

@SergioBenitez I'm going to close this PR. I don't like how its done here. Mainly I now see that `rocket::Config` should not be touched and instead `rocket::custom` should accept a second argument of `T: Into<Option<slog::Drain>>`.

---

As to where to go from here. We can discuss this in #5.

**Comment by 3Hren** [comment]
@mehcode those benchmarks are from my custom proxy server based on tokio-minihttp with slog adaptor for log crate and with all logs disabled at startup using severity filter.

No rocket-rs was used, those post was JFYI.

**Comment by mehcode** [comment]
@3Hren What configuration did you use for slog? Async? How frequent are the logs? I'd be curious to see code as slog claims very high performance with benchmarks to back it up.

**Comment by 3Hren** [comment]
It does not matter whether it was sync or async, because all logs were disabled with `slog-envlogger` at startup.
The frequency was about 30*6300=180k logging attempts per second at peak, where atomic spinning occurred. After that, an application was considered dead, because it did nothing except livelocking around logger inside.

Configuration: linux 3.18 with 32core numa.

Unfortunately I've dropped all associated-with-slog code to prove that. All is left - a benchmark plot, which I showed, but I think it can be easily reproduced. Just take http application with dozen logs per single HTTP request, configure with `slog` logging adapter for `log` crate and fire.

**Comment by mehcode** [comment]
> It does not matter whether it was sync or async, because all logs were disabled with 

From what I understand it does. Logs are "filtered out" as part of your drain configuration so it isn't a simple if check like it is in `log`. When using the asynchronous adapter it's a rough ~100ns per log attempt with the remainder of the work happening in its own thread.

On another note.. there is at least one easy way to optimize your logging setup. `slog` includes a way to compile out log levels. If you only ever want warn+ to ever fire in production you can setup info- to be compiled out. 

If neither of those work, I'd be really interested to have an easy to benchmark sample app that we could present to the people over at slog.

**Pull request closed without merging**
