### PR TITLE
Enable/disable the colorful log

### PR DESCRIPTION
**Pull request by m19c**
This Pull-Request introduces a new way to enable/disable the colorful log output.
Instead of using the environment variable `ROCKET_CLI_COLORS` you can also use the Config itself to do so.

Example:

```
config.enable_colorful_logging();

// or

config.disable_colorful_logging();
```

### CODE REVIEW

**Comment by jhpratt** [comment]
Following the existing pattern in that module, an API of `.set_colorful_logging(bool)` seems more in line than `.{enable|disable}_colorful_logging()`.

**Comment by m19c** [comment]
You are right. There is no enable/disable so far... I'll change it to `set_colorful_logging`.

should i add tests?

**Comment by m19c** [comment]
done.

if I have to add tests:
where would be a good place for it (as far as I can see there are no tests for `Config`)?

**Comment by m19c** [comment]
Ping

**Comment by jebrosen** [comment]
This looks relatively complex for something that feels like it should be a simple change.

What is the motivation for having this rather than doing (for example) `std::env::set_var("ROCKET_CLI_COLORS", "off");`?

**Pull request closed without merging**
