### PR TITLE
Work around rustup issue

### PR DESCRIPTION
**Pull request by retep998**
Enable appveyor please.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Have you tested that this works? Can your provide a screenshot of it working?

**Comment by retep998** [comment]
https://ci.appveyor.com/project/retep998/rocket/build/1.0.2

**Comment by SergioBenitez** [comment]
Thanks! Any chance you'd rewrite the install script stuff in `sh`? I figure many more people know `sh` than PowerShell. If not, I can do it.

**Comment by retep998** [comment]
Considering commands in an appveyor script are executed in either `cmd` or `powershell` but never `sh`, I'm not sure what you mean. Feel free to adjust them yourself if you want. I just copied them from another project of mine.

**Comment by SergioBenitez** [comment]
Sorry, I just meant `cmd`.

**Comment by SShrike** [comment]
I haven't looked at a lick of Powershell in my life, yet I can understand what the scripts do. I don't feel like they are that complicated to understand or modify. If there really is something you don't understand, Google is on and hand and he's *really* good at answering your questions.

**Comment by retep998** [comment]
Microsoft is moving to make Powershell the default option on Windows anyway, because it's just so much better than cmd, so if anything we should be motivating people to switch to Powershell.

(Also since when is Google male?)

**Comment by SShrike** [comment]
@retep998 Well, **he's** not, unless you take [this video](https://www.youtube.com/watch?v=YuOBzWF0Aws) as gospel. :p

But in any case, you must've read the old message, as I had edited it a minute or so after posting because I wasn't happy with the structure of my last sentence.

**Comment by SergioBenitez** [comment]
Building on Appveyor has been incredibly inconsistent. Even now, I can't get builds to work on Appveyor due to a SQLite3 linking issue. Hopefully Rust on Windows will improve to the point that we can use the default tools to test consistently. Unfortunate, this just isn't the case now, and so I'm closing this.

**Pull request closed without merging**
