### PR TITLE
Upgrade tokio-tungstenite to 0.20

### PR DESCRIPTION
**Pull request by fenhl**

### CODE REVIEW

**Comment by SergioBenitez** [comment]
What's changed? Can you share why this version bump is just okay to do?

**Comment by fenhl** [comment]
In tungstenite 0.20, new methods for writing data have been added that no longer implicitly flush the sinks, and the previous methods with implicit flushing have been deprecated. Since there are no deprecation warnings, I believe rocket-ws is not affected by the breaking change.

**Review by SergioBenitez — APPROVED** [review]
LGTM

**Comment by SergioBenitez** [comment]
Merged into master! Thank you.

**Pull request closed without merging**
