### PR TITLE
Draft: Allow specifying a cache-control header for serving static files.

### PR DESCRIPTION
**Pull request by dermesser**
Hi, first-time contributor here! I'd like to request some comments on this change before finalizing it and writing tests.

The idea is that when serving e.g. Javascript or image assets through Rocket, I'd like clients not to request the whole resource every time. I haven't found an established way of doing this in Rocket (except for serving static resources from a different webserver).

It's unclear to me if my solution is too hacky, but I've also not found a better place to implement this in. Maybe you can point me to it if there is.

### CODE REVIEW

**Comment by Zusier** [comment]
Not sure if this is useful here or not but, I currently use this to allow any type that implements a `Responder` trait to have a cache-control header:
```rust
use rocket::response;

pub struct CacheableResponse<T> {
    pub data: T,
    pub cache_control: String,
}

impl<'r, 'o: 'r, T: response::Responder<'r, 'o>> response::Responder<'r, 'o> for CacheableResponse<T> {
    fn respond_to(self, req: &'r rocket::Request<'_>) -> response::Result<'o> {
        response::Response::build_from(self.data.respond_to(req)?)
            .raw_header("Cache-Control", self.cache_control)
            .ok()
    }
}
```

**Comment by dermesser** [comment]
@Zusier thank you, this is my "backup plan", so to say :) I proposed adding this to the file serving code as it is likely a frequent need but I'm ok if your way is the "official" way going forward. (in that case I may file a PR for the documentation later :)

**Comment by JockeTF** [comment]
I wanted to bundle my assets into a single binary, so I did [something slightly different](https://github.com/JockeTF/sopaste/blob/master/src/static.rs). Perhaps that's a bit too specific to be of any help help in this case though.

**Comment by SergioBenitez** [comment]
Please see https://github.com/SergioBenitez/Rocket/issues/95#issuecomment-1492637801.

**Pull request closed without merging**
