### PR TITLE
Implement #1560

### LINKED ISSUE #1560: It would be nice if Forward could include a Error to return if Forwarding fail to find another route
Imagine you have two routes,  

``` rust
#[get("/one")]
pub async fn get_protected_endpoint(user: Authenticated){}
#[get("/one", rank = 2)]
pub async fn get_public_endpoint(){}

#[get("/two")]
pub async fn get_protected_endpoint(user: Authenticated){}
```

A guard takes care of enforcing Authenticated.

if the guard returns Outcome::Error wrapping NotAuthorized, then the second route for /one will never get called 

If the guard returns Outcome::Forward, then for /two the final result will be NotFound instead of UnAuthorized.

If Forward could return a Error, then the routing could be "Try and find another matching route. If nothing works, then return this error"

So Forward(NotAuthorized) would represent this case

To work around this, you need a dummy catchall route to return 'unauthorized', or mess around with a special fairing.

### PR DESCRIPTION
**Pull request by bewee**
This aims to close #1560

### CODE REVIEW

**Comment by bewee** [comment]
Hi, I just stumbled across this old PR and saw that it gathered some conflicts. Is there still any interest in this feature? Then I could try to resolve the conflicts

**Comment by bewee** [comment]
Hello??? @SergioBenitez ? Anybody here? Just any life sign, please?

**Comment by LMH01** [comment]
Hello @bewee 

I would really appreciate if you would resolve the conflicts and if this pull request could be merged as I stumbled across a problem where I would require this feature.

**Comment by SergioBenitez** [comment]
Merged in https://github.com/SergioBenitez/Rocket/commit/055ad107df9753765c2cfe02bccb99942750d57d! Thank you!

**Pull request closed without merging**
