### PR TITLE
Add test to check for working condition. Expose fn to get rocket and …

### PR DESCRIPTION
**Pull request by StefanoChiodino**
…run rust fmt

Partially solves #62

### CODE REVIEW

**Comment by StefanoChiodino** [comment]
Hi, @SergioBenitez have you had a chance to look at this?

**Comment by SergioBenitez** [comment]
Thanks so much for this, and sorry for the delay in getting back to you. I'm excited to see you contribute these tests in! I've left some feedback. Please let me know if you have any questions. :)

**Comment by StefanoChiodino** [comment]
That's great @SergioBenitez, thanks for the feedback. The review points are all fine (though I personally would call something that just returns rocket `get_rocket` but I saw it being called just `rocket` in other places and I get the point for consistency!).

I expected the lack of tests for failure to come up, but wanted to show what I've got so far. Shouldn't be too difficult to add a few more!

Cheers

**Comment by StefanoChiodino** [comment]
I think I've addressed all you points. I tried passing a string that doesn't serialise to a form struct and  an invalid utf8, then check for the expected error.

**Comment by SergioBenitez** [comment]
Sorry, I may not have been clear. We're not too concerned about getting invalid UTF8 at the application side; I think it's okay to assume that, though it's also fine to test. But we _do_ want to test for validation. We want to make sure that, for example, a form field 'radio' with value 'D' doesn't parse. In other words, we want to make sure that the validation we _think_ is happening is indeed happening.

We should test each of the form fields. So, we'd have 6 classes of tests, one for each field. We want to isolate each field, so each class of tests would use valid values for all fields but the one being tested. For instance, to test the `radio` field, we'd use valid values for all other fields, then perhaps have three tests:

   * One with a valid value for `radio`: should pass.
   * One with `radio` missing: should fail.
   * One with an invalid value for `radio`: should fail.

This gives us thorough testing of the form example.

**Comment by SergioBenitez** [comment]
@StefanoChiodino Do you think you'll be able to take care of this? :)

**Comment by SergioBenitez** [comment]
@StefanoChiodino I wanted to close out #62, so I went ahead and implemented the tests for the 'form_kitchen_sink' example myself. Please do contribute again in the future! It's more than appreciated it!

**Pull request closed without merging**
