### PR TITLE
Fixes #1454: Remove unnecessary .as_str()

### LINKED ISSUE #1454: Simplify RawStr usage in dynamic paths documentation
Link: https://rocket.rs/v0.4/guide/requests/#dynamic-paths

Location: First code snippet line 3

Existing line:

```rust
    format!("Hello, {}!", name.as_str())
```

Simplified usage to get the same result:

```rust
    format!("Hello, {}!", name)
```

### PR DESCRIPTION
**Pull request by Compro-Prasad**
From Dynamic Paths section

### CODE REVIEW

**Review by SergioBenitez — APPROVED** [review]
Sure!

**Comment by Compro-Prasad** [comment]
I also found another thing that can be simplified in the Optional parameters section.

Before:
```rust
#[get("/hello?wave&<name>")]
fn hello(name: Option<String>) -> String {
    name.map(|name| format!("Hi, {}!", name))
        .unwrap_or_else(|| "Hello!".into())
}
```

After:
```rust
#[get("/hello?wave&<name>")]
fn hello(name: Option<String>) -> String {
    name.map_or("Hello!".into(), |name| format!("Hi, {}!", name))
}
```

**Comment by SergioBenitez** [comment]
> I also found another thing that can be simplified in the Optional parameters section.
> 
> Current:
> 
> ```rust
> #[get("/hello?wave&<name>")]
> fn hello(name: Option<String>) -> String {
>     name.map(|name| format!("Hi, {}!", name))
>         .unwrap_or_else(|| "Hello!".into())
> }
> ```
> 
> New:
> 
> ```rust
> #[get("/hello?wave&<name>")]
> fn hello(name: Option<String>) -> String {
>     name.map_or("Hello!".into(), |name| format!("Hi, {}!", name))
> }
> ```
> 
> Should I add these changes in this commit?

These are not semantically identical: the "new" version always allocates the string `"Hello!"` while the "old" does not; we should prefer the "old".

**Comment by SergioBenitez** [comment]
Merged with a few changes in b7565172eb07e64e35e3cbb3d762281e001dc77e. Thanks!

**Comment by SergioBenitez** [comment]
Merged in de1cffba462da13f6a5db3b6722e05ae7c46641f. Thank you, and apologies for the noise!

**Pull request closed without merging**
