### PR TITLE
Allow for pretty debugging everywhere

### PR DESCRIPTION
**Pull request by jhpratt**

### CODE REVIEW

**Comment by jhpratt** [comment]
Looks like the build failures are unrelated. When running `cargo check` on my machine (using an older nightly), it works fine.

**Comment by jebrosen** [comment]
Any objections to merging this into `master` instead?

**Comment by jhpratt** [comment]
I have none. I'll change the branch and re-push in a bit.

We're you thinking of including this in the possible 0.4.3 release?

**Comment by jebrosen** [comment]
I didn't have that in mind, but that's enough to convince me it really should be in `master`!

**Comment by SergioBenitez** [comment]
Looks good to me!

**Comment by SergioBenitez** [comment]
Merged in bed93133b8bc7d206893bbf823f7fdfeb6222325. Thank you!

**Pull request closed without merging**
