### PR TITLE
[WIP] convert serve module to async/await

### PR DESCRIPTION
**Pull request by Redrield**
Converting serve.rs and associated tests to use async/await

### CODE REVIEW

**Comment by Redrield** [comment]
I've marked this as WIP for now as I'm having issues getting the tests to pass. Trying to block on the file IO is giving errors somewhere down the line on my machine, but I can't pinpoint where. [Example of what it's doing](https://0x0.st/zOrv.png)

**Comment by jebrosen** [comment]
Oh bother, I have thought and forgot about this little detail before. The problem here is that I had used tokio's `File` to implement the `File` responder, which doesn't work outside of tokio. But `.body_bytes_wait()` uses the `futures-rs` executor. Fixing this should be a relatively small code change but is a pretty significant design issue to consider.

**Comment by Redrield** [comment]
Will it be something considered in discussion on the tracking issue? I can put this on hold until something is reached and then either add the change to this PR or open a new one with the change to fix the tests for this.

**Comment by jebrosen** [comment]
Let's put this one on hold for the moment - and anything else to do with `File`, sadly. It's harder to fix than I realized because `tokio` 0.1's "block_on" equivalent requires the future to be `'static`. #1071 should make this easier to fix.

**Comment by jebrosen** [comment]
I merged this without rustfmt-induced changes in 5b1125b. Thanks!

**Pull request closed without merging**
