### PR TITLE
No longer rewrite all request remotes.

### PR DESCRIPTION
**Pull request by almielczarek**
With this set of changes, a request's remote is always that of the peer connection.

If an application needs to get the value out of the "X-Real-IP" header, authors should use the newly added real_ip function.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Please rebase on master and resolve the build issues.

**Comment by almielczarek** [comment]
Sorry. I had trailing whitespace in the previous commits.

**Comment by SergioBenitez** [comment]
Hmm. Did you rebase and then force push (which should work)? GitHub is confused.

**Comment by SergioBenitez** [comment]
Merged in c2899b23910472a526adca1544d524317c35123c. Thank you, kindly, for taking this on and seeing it through! :)

**Pull request closed without merging**
