### PR TITLE
updated serde to v1

### PR DESCRIPTION
**Pull request by skariel**
otherwise it doesn't work with projects using serde 0.9

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Unfortunately we need both Tera and Handlebars to upgrade to v1.0 before we can.

**Comment by skariel** [comment]
well, I'll do PRs for them too then

**Comment by skariel** [comment]
Done: upgrading serde v1 PRs for Rocket, Tera and Handlebars-Rust

**Comment by sunng87** [comment]
Handlebars 0.26.1 released for serde 1.0

**Pull request closed without merging**
