### PR TITLE
Implement compression for the async version

### PR DESCRIPTION
**Pull request by dnaka91**
I started off a new small project where I'm using the async branch and noticed that the compression feature is not ported over yet.

So I ported it to use `async-compression` which also gives a much nicer interface to the brotli de-/encoder.

Currently `async-compression` doesn't natively support the `AsyncRead` of `tokio` yet, so I needed to add `tokio-util` as a bridge between the `tokio` and `futures` crates.

The re-enabled tests all pass but I didn't do any manual testing so far.

### CODE REVIEW

**Comment by jebrosen** [comment]
> Currently `async-compression` doesn't natively support the `AsyncRead` of `tokio` yet, so I needed to add `tokio-util` as a bridge between the `tokio` and `futures` crates.

I know this is planned: https://github.com/Nemo157/async-compression/issues/57. I won't review this for at least a few days, and I'll watch that issue carefully and try to get a sense of when that might land.

I will likely want to make some additional changes before integration - configuration is one potential example (to try to mesh better with #852). I thought of at least one other possible problem while reviewing #887: `Compression` is not composable with certain other transformations such as `Content-Range`, and that should be enforced and/or documented properly.

**Comment by dnaka91** [comment]
Thank you for your comment @jebrosen.

I agree, in the end it would be good to have a direct integration from `async-compression` that we could use. Also, I read the other issues you mentioned and believe that they are important too as the current compression implementation is rather basic.

I created the PR to have at least some kind of compression feature in the async branch and use it as starting point for further improvements.

**Comment by dnaka91** [comment]
The maintainer of the `async-compression` crate just added direct support for the `tokio` traits so I updated my PR. I integrated the latest changes from the `async` branch as well.

**Comment by SergioBenitez** [comment]
Hi! This PR was closed automatically by GitHub. If this is still relevant, please open a new PR!

**Comment by phayes** [comment]
It seems that this is still needed.  Can we reopen this?

**Comment by SergioBenitez** [comment]
> It seems that this is still needed.  Can we reopen this?

This PR is quite a bit behind the tip, so it's unlikely to be useful in its current state. If you'd like to push it forward, please rebase these commits on the current master and open a new PR.

**Pull request closed without merging**
