### PR TITLE
Fix #1067 by importing typed headers from hyperx

### LINKED ISSUE #1067: (async) Remove or replace of typed headers
Typed headers were removed between hyper 0.10 and hyper 0.12. `typed-headers` does not appear to have all the headers hyper 0.10 did, but it looks like `hyperx` might.

Options:
* Re-export headers from one or the other library - this is what we did with hyper 0.10
* Remove typed header support - this is currently implemented in the `async` branch; only the header names are available in hyper and we re-export those.
* Implement `From<X> for Header` for every header in one or both of `hyperx` and `typed-headers`, perhaps behind a feature flag

### PR DESCRIPTION
**Pull request by jespersm**
First attempt patch for #1067.

Imports all typed headers from `hyperx` except "Set-Cookie" since it requires multiline format, and thus can't do simple to_string().

Probably not a big deal since Rocket handles cookies through CookieJar mechanism.

### CODE REVIEW

**Comment by jespersm** [comment]
I think this PR is ready for review now, @jebrosen :-)

I'm not entirely sure that the reexport of HyperxHeaderTrait is elegant enough, but there's a "Header" confusion to take into account.

**Review by jebrosen — CHANGES_REQUESTED** [review]
I do like this, but I think we can organize it a bit more nicely.

One thing I did realize while reviewing this is that `hyperx` does not implement some of traits `hyper` uses it for headers, cc #1498. That's one point in favor of `headers` instead of `hyperx` that I did not consider, depending on how we prioritize #1498.

**Comment by jespersm** [comment]
I’ll take another look at #1498 to see how this interacts.

**Comment by jespersm** [comment]
I've looked further at `headers`, which appears to use a `HeaderValue` struct from `headers-core`, which is yet another one,  different one from the `HeaderValue` in `hyper`. That doesn't seem to line up with the change proposed in #1498, but I might not be Rust-y enough to know if there's a simple way to do that without cloning the underlying bytes.

**Comment by jebrosen** [comment]
> I've looked further at `headers`, which appears to use a `HeaderValue` struct from `headers-core`, which is yet another one, different one from the `HeaderValue` in `hyper`. That doesn't seem to line up with the change proposed in #1498, but I might not be Rust-y enough to know if there's a simple way to do that without cloning the underlying bytes.

Both `headers-core`'s and `hyper`'s `HeaderValue` types are actually re-exports of `http::headers::HeaderValue` (<https://docs.rs/headers-core/0.2.0/src/headers_core/lib.rs.html#13>, <https://docs.rs/hyper/0.14.4/src/hyper/lib.rs.html#73>).

@SergioBenitez is #1498 enough of a concern that we should avoid using `hyperx` to provide typed headers, which currently has non-zero overhead to be converted to the `HeaderValue` type used by `hyper`?

**Comment by jespersm** [comment]
> Both `headers-core`'s and `hyper`'s `HeaderValue` types are actually re-exports of `http::headers::HeaderValue` (https://docs.rs/headers-core/0.2.0/src/headers_core/lib.rs.html#13, https://docs.rs/hyper/0.14.4/src/hyper/lib.rs.html#73).

Ah, I was confused by a layer of turtles.

Anyway, I'm giving #1498 a shot to see how big an impact it would have.

**Comment by SergioBenitez** [comment]
> @SergioBenitez is #1498 enough of a concern that we should avoid using `hyperx` to provide typed headers, which currently has non-zero overhead to be converted to the `HeaderValue` type used by `hyper`?

I believe this is the single largest source of slowdown in request handling. We should do nothing to exacerbate the issue or further prolong its mending.

**Comment by SergioBenitez** [comment]
> @SergioBenitez #1498 addressed handling of headers in the request, but didn't touch `Response`s which still unconditionally copies data as it did in 0.4 (https://github.com/SergioBenitez/Rocket/blob/master/core/lib/src/server.rs#L130). What needs to happen to implement this with the desired performance characteristics?

I don't think there's anything we can reasonable do about the response, unfortunately. See https://github.com/hyperium/http/pull/467. Hopefully we get an upstream fix.

**Comment by SergioBenitez** [comment]
I am closing this due to lack of progress. Happy to revisit if all of the points raised above are addressed.

**Pull request closed without merging**
