### PR TITLE
Example of responding using a custom enum type

### PR DESCRIPTION
**Pull request by raboof**
As a ready-to-go alternative to using Either.

### CODE REVIEW

**Comment by raboof** [comment]
(just found `scripts/test.sh` from the travis config, will make sure that passes ;) )

**Comment by raboof** [comment]
Hm I seem to have confused travis... "GitHub payload is missing a merge commit (mergeable_state: "unknown", merged: false)'"

**Comment by SergioBenitez** [comment]
Copying over from IRC:

```
[13:20:02]  ~Sergio: raboof: I don't think you need any of those features in the doctest.
[13:20:09]  ~Sergio: Nor the `extern crate rocket;` line.
[13:20:24]  ~Sergio: Killing the first four lines should get your code to compile.
```

**Comment by raboof** [comment]
(feel free to squash on merge of course :) )

**Comment by SergioBenitez** [comment]
This will be largely obsoleted by `Responder` derives (#590). Closing in favor of that.

**Pull request closed without merging**
